"""Append-only build history — REBUILD.md §7.

``server/models/builds.jsonl``: one JSON line per from-scratch build attempt. Under
the data-centric rebuild an adapter is a **build artifact** (a pure function of the
frozen base + bundle corpus + config), never a resumed lineage — so the durable
consolidation clock is no longer the ledger's decay *stage* but this log. It is:

  * the source for ``age()`` — how many builds have **promoted** since a bundle was
    reflected (the analogue of the retired decay stage; drives the bundle's LR
    multiplier, REBUILD.md §1);
  * the reproducibility record (corpus fingerprint + base LR per build); and
  * the instrumentation spine (probe outcome per build).

A **rejected** build advances no bundle's age (only ``promoted`` lines count), which
is the rebuild analogue of "no stage advance on veto".
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

BUILDS_FILE = "builds.jsonl"


class BuildHistory:
    """Folded view + writer for ``models/builds.jsonl`` (append-only, one line/build)."""

    def __init__(self, models_dir: Path) -> None:
        self.path = Path(models_dir) / BUILDS_FILE

    # -- reads ------------------------------------------------------------- #

    def _read(self) -> list[dict]:
        if not self.path.exists():
            return []
        out: list[dict] = []
        try:
            for line in self.path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    out.append(json.loads(line))
                except Exception:
                    continue
        except Exception:
            return []
        return out

    def promoted(self) -> list[dict]:
        """All build records whose probe passed (or was skipped) and adapter promoted."""
        return [r for r in self._read() if r.get("outcome") == "promoted"]

    def age_of(self, reflected_at: Optional[str]) -> int:
        """Promoted builds since *reflected_at* — **instrumentation only** now.

        Retained for the build log's own analytics; it is **no longer** the bundle's
        training/RAG age. Under the wall-clock retrofit (REBUILD §1) age is hours since the
        chat, computed by ``decay.wall_clock_age_hours`` — neither ``build_dataset`` nor
        ``rag_engine`` reads this count anymore. ISO timestamps compare lexicographically,
        so a string ``>`` is a correct chronological test; no ``reflected_at`` -> 0.
        """
        ra = (reflected_at or "").strip()
        if not ra:
            return 0
        return sum(1 for r in self.promoted() if str(r.get("ts") or "") > ra)

    # -- writes ------------------------------------------------------------ #

    @staticmethod
    def new_build_id() -> str:
        """A fresh build id — also the forensic snapshot dir name. Pre-generated by the
        caller so the snapshot can be written under it *before* the line is appended (§7)."""
        return f"build-{datetime.now():%Y%m%d-%H%M%S}"

    def append(self, *, outcome: str, rows: int, base_lr: float,
               run_id: Optional[str] = None, corpus_fingerprint: str = "",
               probe_summary: Optional[dict] = None,
               adapter_dir: Optional[str] = None,
               build_id: Optional[str] = None,
               built_at: Optional[str] = None,
               seed: Optional[int] = None,
               snapshot_dir: Optional[str] = None) -> str:
        """Record one build attempt. *outcome* is ``"promoted"`` or ``"rejected"``.

        *built_at* is the build's as_of clock — every row's wall-clock age was measured
        against it, so it (with *seed* + *corpus_fingerprint*) is what makes the build
        reproducible (REBUILD §7). *snapshot_dir* points at the immutable forensic snapshot.
        Pass *build_id* to reuse a pre-generated id (so it matches the snapshot dir name);
        otherwise one is generated. Returns the build_id.
        """
        build_id = build_id or self.new_build_id()
        rec = {
            "build_id": build_id,
            "ts": datetime.now().isoformat(),
            "built_at": built_at,
            "seed": seed,
            "run_id": run_id,
            "corpus_fingerprint": corpus_fingerprint,
            "rows": int(rows),
            "outcome": outcome,
            "base_lr": base_lr,
            "probe_summary": probe_summary or {},
            "adapter_dir": adapter_dir,
            "snapshot_dir": snapshot_dir,
        }
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.path, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
        return build_id
