"""Label inventory — the Track B census (AVA_REWARD_LOOP.md §7 item 4).

One table that answers "can the probe experiment (§4.3) run yet?" from what the box
already holds, without a model:

  * **Identity-channel labels.** Every reflected exchange carries a verdict in its
    ``.state.json`` sidecar (``keep`` / ``revise`` — `chat_sidecar.write_verdict`).
    ``revised ∈ {0,1}`` is that verdict; a banned exchange is not a label. Counted per
    (model, adapter) because a label is only usable with the hidden states of the
    weights that produced the reply.
  * **Hidden-state captures.** Which of those exchanges have residuals in the
    transcript's ``.hidden.npz`` (`core/hidden_capture.py`). A label without a
    capture is still useful: for a chat generated by the CURRENTLY configured
    model + adapter the residuals can be recomputed by a teacher-forced forward pass
    over the stored tokens (§4.3 step 1) — the same weights give the same states.
    For any other weights they cannot, and the label waits for a probe trained on
    those weights.
  * **Epistemic-channel labels.** ASK records by kind and ``surface_count`` from the
    reflection op-log, and ASK attempts with judge verdicts (Track A, §3) — zero
    until items 7–11 exist. Reset tests (§3.7) likewise.

Readiness follows §4.1 of the note: several hundred labelled exchanges (``--min-labeled``,
default 300), ≥ 100 ASK attempts with verdicts, ≥ 10 reset tests. The verdict lines
at the bottom say which precondition holds, and for the identity channel whether the
shortfall is labels (wait for reflection) or captures (backfill, or wait for new chats).

Read-only. GPU-free. ``python -m core.label_inventory [--chats DIR] [--memory DIR]
[--json] [--min-labeled N]`` from ``server/inference``; the ``__main__`` with
``--selftest`` builds a throwaway corpus and checks the counts.
"""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Optional

from core.chat_sidecar import iter_chat_json_files, sidecar_path_for
from core import hidden_capture

# §4.1 thresholds: "≥ several hundred exchanges with revised ∈ {0,1}, ≥ 100 ASK attempts
# with verdicts, ≥ 10 reset tests."
DEFAULT_MIN_LABELED = 300
MIN_ASK_ATTEMPTS = 100
MIN_RESET_TESTS = 10

LABEL_VERDICTS = ("keep", "revise")
# Below this share of `revise` among labelled exchanges the identity probe has too few
# positives to learn from (a 1% positive class is a constant predictor's AUC).
MIN_REVISE_SHARE = 0.05


def adapter_name(adapter_id: str) -> str:
    """The adapter's identity is its directory name (`adapter-<run_id>`): a transcript
    records what the box was configured with, which may be a bare name or an absolute
    path, and the config on another checkout may hold a different path to the same
    adapter. "" stays "" (base)."""
    a = str(adapter_id or "").strip().rstrip("/\\")
    return Path(a).name if a else ""


def _server_dir() -> Path:
    return Path(__file__).resolve().parents[2]


def _paths():
    """(chats_dir, memory_dir, attempts_path, current model_id, current adapter_id)."""
    server_dir = _server_dir()
    if str(server_dir) not in sys.path:
        sys.path.insert(0, str(server_dir))
    from training.reflections_path import hot_chats_dir, memory_dir, load_server_config
    cfg = load_server_config() or {}
    data_dir = Path(__file__).resolve().parents[1] / "data"
    return (hot_chats_dir(), memory_dir(), data_dir / "hot" / "asks" / "attempts.jsonl",
            str(cfg.get("model_id") or ""), str(cfg.get("adapter_id") or ""))


def _load_json(path: Path) -> Optional[dict]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    return data if isinstance(data, dict) else None


# ── the census ───────────────────────────────────────────────────────────────

def inventory_chats(chats_dir: Path) -> dict:
    """Per (model, adapter) counts over every transcript under ``chats_dir``.

    Returns ``{"groups": {(model, adapter): row}, "transcripts": n, "exchanges": n,
    "verdict_values": [...], "first": ts, "last": ts}``. A row: ``exchanges``,
    ``verdicts`` (Counter by value; ``""`` = none), ``banned``, ``locked``,
    ``tension`` (exchanges with a stored per-token series), ``hidden`` (with a
    residual capture), ``axes`` (with axis projections), ``labeled`` (keep/revise,
    not banned), ``labeled_hidden`` (labelled AND captured), ``reflected`` chats.
    """
    groups: dict = {}
    verdict_values: set = set()
    n_tr = n_ex = 0
    first = last = ""

    def row_for(model: str, adapter: str) -> dict:
        key = (model, adapter)
        if key not in groups:
            groups[key] = {
                "model": model, "adapter": adapter, "transcripts": 0, "exchanges": 0,
                "verdicts": Counter(), "banned": 0, "locked": 0, "tension": 0,
                "hidden": 0, "base": 0, "axes": 0, "labeled": 0, "labeled_hidden": 0,
                "reflected": 0,
            }
        return groups[key]

    for chat in iter_chat_json_files(Path(chats_dir)):
        data = _load_json(chat)
        if data is None:
            continue
        exchanges = data.get("exchanges") or []
        if not isinstance(exchanges, list):
            continue
        model = str(data.get("model_id") or "")
        adapter = adapter_name(data.get("adapter_id"))
        row = row_for(model, adapter)
        row["transcripts"] += 1
        n_tr += 1
        ts = str(data.get("timestamp") or chat.stem)
        first = ts if not first or ts < first else first
        last = ts if ts > last else last

        side = _load_json(sidecar_path_for(chat)) or {}
        side_ex = side.get("exchanges") if isinstance(side.get("exchanges"), dict) else {}
        if side.get("reflected_at") or side.get("chat_reflected"):
            row["reflected"] += 1
        sidecar_idx = hidden_capture.sidecar_index(hidden_capture.sidecar_path(chat))
        captured = {r["exchange_id"] for r in sidecar_idx.values() if r["variant"] == ""}
        backfilled = {r["exchange_id"] for r in sidecar_idx.values() if r["variant"]}
        sidecar_axes = {r["exchange_id"] for r in sidecar_idx.values() if r["axes"]}

        for i, ex in enumerate(exchanges):
            if not isinstance(ex, dict):
                continue
            row["exchanges"] += 1
            n_ex += 1
            rec = side_ex.get(str(i)) if isinstance(side_ex.get(str(i)), dict) else {}
            verdict = str(rec.get("verdict") or "").strip().lower()
            row["verdicts"][verdict] += 1
            if verdict:
                verdict_values.add(verdict)
            banned = bool(rec.get("banned"))
            row["banned"] += int(banned)
            row["locked"] += int(bool(rec.get("locked")))
            tension = ex.get("tension") if isinstance(ex.get("tension"), dict) else {}
            has_series = bool(tension.get("token_ids"))
            row["tension"] += int(has_series)
            key = hidden_capture.exchange_key(ex, i)
            row["axes"] += int(bool(tension.get("axes")) or key in sidecar_axes)
            has_hidden = key in captured           # live, under the weights that replied
            has_base = key in backfilled            # a backfill under other weights
            row["hidden"] += int(has_hidden)
            row["base"] += int(has_base)
            labeled = verdict in LABEL_VERDICTS and not banned
            row["labeled"] += int(labeled)
            row["labeled_hidden"] += int(labeled and (has_hidden or has_base))

    return {"groups": groups, "transcripts": n_tr, "exchanges": n_ex,
            "verdict_values": sorted(verdict_values), "first": first, "last": last}


def inventory_asks(memory_dir: Path, attempts_path: Optional[Path] = None) -> dict:
    """ASK records from the op-log: live by kind, resolved (evicted) by kind, the
    ``surface_count`` histogram of live asks, and Track A attempts / reset tests."""
    path = Path(memory_dir) / "rag_memory.jsonl"
    kinds: dict[str, str] = {}
    live: dict[str, dict] = {}
    resolved: Counter = Counter()
    surfaces: Counter = Counter()
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except Exception:
                continue
            key = rec.get("key")
            if not key:
                continue
            op = rec.get("op")
            if op == "insert":
                if rec.get("kind") == "ask":
                    kinds[key] = str(rec.get("ask_kind") or "?")
                    live[key] = rec
                else:
                    live.pop(key, None)
            elif op in ("evict", "supersede"):
                if key in live:
                    resolved[kinds.get(key, "?")] += int(op == "evict")
                live.pop(key, None)
            elif op == "surface":
                surfaces[key] += 1
    live_by_kind: Counter = Counter(kinds[k] for k in live)
    hist: Counter = Counter()
    for k in live:
        n = surfaces.get(k, 0)
        hist["0" if n == 0 else "1" if n == 1 else "2" if n == 2 else "3+"] += 1

    attempts = attempts_with_verdict = 0
    if attempts_path is not None and Path(attempts_path).exists():
        for line in Path(attempts_path).read_text(encoding="utf-8").splitlines():
            try:
                rec = json.loads(line)
            except Exception:
                continue
            attempts += 1
            if isinstance(rec, dict) and rec.get("verdict"):
                attempts_with_verdict += 1
    return {
        "live": dict(live_by_kind), "live_total": len(live),
        "resolved": dict(resolved), "resolved_total": sum(resolved.values()),
        "surface_hist": dict(hist),
        "attempts": attempts, "attempts_with_verdict": attempts_with_verdict,
        "reset_tests": 0,   # §3.7: nothing writes them yet
        "op_log": str(path), "op_log_exists": path.exists(),
    }


def readiness(chats: dict, asks: dict, *, current_model: str, current_adapter: str,
              min_labeled: int = DEFAULT_MIN_LABELED) -> dict:
    """The §4.1 preconditions against the counts, with the identity shortfall named."""
    groups = chats["groups"]
    current_adapter = adapter_name(current_adapter)
    labeled = sum(r["labeled"] for r in groups.values())
    labeled_hidden = sum(r["labeled_hidden"] for r in groups.values())
    revised = sum(r["verdicts"].get("revise", 0) for r in groups.values())
    revise_share = (revised / labeled) if labeled else 0.0
    cur = groups.get((current_model, current_adapter))
    cur_labeled = cur["labeled"] if cur else 0
    cur_hidden = cur["labeled_hidden"] if cur else 0
    backfillable = cur_labeled - cur_hidden
    other_labeled = labeled - cur_labeled
    identity = {
        "labeled": labeled,
        "labeled_hidden": labeled_hidden,
        "current_labeled": cur_labeled,
        "current_labeled_hidden": cur_hidden,
        "current_backfillable": backfillable,
        "other_weights_labeled": other_labeled,
        "min_labeled": min_labeled,
        "revised": revised,
        "revise_share": revise_share,
        "balance_ok": revise_share >= MIN_REVISE_SHARE,
        "labels_ready": labeled >= min_labeled,
        "current_labels_ready": cur_labeled >= min_labeled,
        "captures_ready": cur_hidden >= min_labeled,
    }
    if cur_hidden >= min_labeled:
        identity["verdict"] = "READY — captured labels under the current weights meet the floor"
    elif cur_labeled >= min_labeled:
        identity["verdict"] = (f"LABELS READY, CAPTURES SHORT — {backfillable} labelled exchanges "
                               f"under the current weights lack residuals: backfill them with a "
                               f"forward pass over the stored tokens (§4.3 step 1), or wait for "
                               f"new chats")
    elif labeled >= min_labeled:
        identity["verdict"] = (f"LABELS EXIST BUT UNDER OTHER WEIGHTS — {other_labeled} of {labeled} "
                               f"were produced by a model/adapter that is not the current one; a "
                               f"probe must be trained per weights (P6). Under the current: "
                               f"{cur_labeled}")
    else:
        identity["verdict"] = (f"NOT READY — {labeled} labelled exchanges, floor {min_labeled}: "
                               f"more reflected chats needed")
    if labeled and revise_share < MIN_REVISE_SHARE:
        identity["verdict"] += (f"; CLASS BALANCE — revise is {revised} of {labeled} "
                                f"({revise_share * 100:.1f}%), below {MIN_REVISE_SHARE * 100:.0f}%: "
                                f"the identity label is nearly constant, a probe on it cannot "
                                f"be evaluated; count `revise` as it accrues or widen the label")
    epistemic = {
        "attempts_with_verdict": asks["attempts_with_verdict"],
        "min": MIN_ASK_ATTEMPTS,
        "ready": asks["attempts_with_verdict"] >= MIN_ASK_ATTEMPTS,
        "verdict": ("READY" if asks["attempts_with_verdict"] >= MIN_ASK_ATTEMPTS else
                    f"NOT READY — {asks['attempts_with_verdict']} ASK attempts with a judge "
                    f"verdict, floor {MIN_ASK_ATTEMPTS} (Track A, §7 items 7–11)"),
    }
    reset = {
        "count": asks["reset_tests"], "min": MIN_RESET_TESTS,
        "ready": asks["reset_tests"] >= MIN_RESET_TESTS,
        "verdict": ("READY" if asks["reset_tests"] >= MIN_RESET_TESTS else
                    f"NOT READY — {asks['reset_tests']} reset tests, floor {MIN_RESET_TESTS} "
                    f"(§3.7, item 12)"),
    }
    return {"identity": identity, "epistemic": epistemic, "reset": reset}


def build(chats_dir: Path, memory_dir: Path, attempts_path: Optional[Path], *,
          current_model: str, current_adapter: str,
          min_labeled: int = DEFAULT_MIN_LABELED) -> dict:
    chats = inventory_chats(chats_dir)
    asks = inventory_asks(memory_dir, attempts_path)
    ready = readiness(chats, asks, current_model=current_model,
                      current_adapter=current_adapter, min_labeled=min_labeled)
    try:
        from core import revision_ledger
        ledger = revision_ledger.summarize(revision_ledger.read_events(chats_dir))
    except Exception:
        ledger = {}
    return {"chats": chats, "asks": asks, "readiness": ready, "ledger": ledger,
            "current": {"model": current_model, "adapter": current_adapter}}


# ── rendering ────────────────────────────────────────────────────────────────

def _short(s: str, n: int) -> str:
    s = s or "—"
    return s if len(s) <= n else "…" + s[-(n - 1):]


def render(report: dict) -> str:
    chats, asks, ready = report["chats"], report["asks"], report["readiness"]
    cur = report["current"]
    values = [v for v in chats["verdict_values"]]
    lines = []
    lines.append(f"LABEL INVENTORY — {chats['transcripts']} transcripts, {chats['exchanges']} "
                 f"exchanges ({chats['first'] or '—'} … {chats['last'] or '—'})")
    lines.append(f"current weights: {cur['model'] or '—'} + {adapter_name(cur['adapter']) or 'base'}")
    lines.append("")
    head = ["model", "adapter", "chats", "refl", "exch"] + values + \
           ["none", "ban", "lock", "tens", "hid", "base", "axes", "label", "lab+hid"]
    widths = [28, 22, 5, 4, 5] + [max(6, len(v)) for v in values] + [5, 4, 4, 5, 5, 5, 4, 5, 7]
    def fmt(cells):
        return "  ".join(str(c).ljust(w) if i < 2 else str(c).rjust(w)
                         for i, (c, w) in enumerate(zip(cells, widths)))
    lines.append(fmt(head))
    lines.append(fmt(["-" * w for w in widths]))
    rows = sorted(chats["groups"].values(), key=lambda r: -r["exchanges"])
    for r in rows:
        mark = "*" if (r["model"], r["adapter"]) == (cur["model"], adapter_name(cur["adapter"])) else " "
        cells = [mark + _short(r["model"], 27), _short(r["adapter"] or "base", 22),
                 r["transcripts"], r["reflected"], r["exchanges"]]
        cells += [r["verdicts"].get(v, 0) for v in values]
        cells += [r["verdicts"].get("", 0), r["banned"], r["locked"], r["tension"],
                  r["hidden"], r["base"], r["axes"], r["labeled"], r["labeled_hidden"]]
        lines.append(fmt(cells))
    if len(rows) > 1:
        tot = defaultdict(int)
        for r in rows:
            for k in ("transcripts", "reflected", "exchanges", "banned", "locked", "tension",
                      "hidden", "base", "axes", "labeled", "labeled_hidden"):
                tot[k] += r[k]
            for v in values + [""]:
                tot["v:" + v] += r["verdicts"].get(v, 0)
        cells = [" total", "", tot["transcripts"], tot["reflected"], tot["exchanges"]]
        cells += [tot["v:" + v] for v in values]
        cells += [tot["v:"], tot["banned"], tot["locked"], tot["tension"], tot["hidden"],
                  tot["base"], tot["axes"], tot["labeled"], tot["labeled_hidden"]]
        lines.append(fmt(cells))
    lines.append("  * = current weights · refl = chats frozen by reflection · none = no verdict yet · "
                 "tens = stored per-token series · hid = live residual capture · base = backfilled "
                 "capture (other weights) · axes = axis projections · label = keep/revise and not "
                 "banned · lab+hid counts either capture")
    lines.append("")
    live = asks["live"]
    lines.append(f"ASK records ({'op-log at ' + asks['op_log'] if asks['op_log_exists'] else 'no op-log'}):")
    lines.append(f"  live {asks['live_total']}: " +
                 (", ".join(f"{k} {live[k]}" for k in sorted(live)) or "—") +
                 f"   ·   resolved {asks['resolved_total']}: " +
                 (", ".join(f"{k} {asks['resolved'][k]}" for k in sorted(asks['resolved'])) or "—"))
    hist = asks["surface_hist"]
    lines.append("  live by surface_count: " +
                 (", ".join(f"{k}× {hist[k]}" for k in ("0", "1", "2", "3+") if k in hist) or "—"))
    lines.append(f"  attempts {asks['attempts']} (with verdict {asks['attempts_with_verdict']})   ·   "
                 f"reset tests {asks['reset_tests']}")
    lines.append("")
    led = report.get("ledger") or {}
    if led.get("events"):
        lines.append(f"REVISIONS LEDGER: {led['events']} events, {led['verdict_events']} verdict events "
                     f"over {led['distinct_exchanges']} exchanges ("
                     + ", ".join(f"{k or '?'} {v}" for k, v in sorted(led["by_verdict"].items()))
                     + f"); with WHY {led['with_why']}, flips {led['flips']}, truncated {led['truncated']}, "
                     f"annotations {led['annotations']}")
    else:
        lines.append("REVISIONS LEDGER: empty — fills from the next reflection (Sleep or background)")
    lines.append("")
    lines.append("READINESS (§4.1):")
    i = ready["identity"]
    lines.append(f"  identity  labelled {i['labeled']} (captured {i['labeled_hidden']}); under current "
                 f"weights {i['current_labeled']} (captured {i['current_labeled_hidden']}, "
                 f"backfillable {i['current_backfillable']}); floor {i['min_labeled']}")
    lines.append(f"            → {i['verdict']}")
    lines.append(f"  epistemic → {ready['epistemic']['verdict']}")
    lines.append(f"  reset     → {ready['reset']['verdict']}")
    return "\n".join(lines)


def _jsonable(obj: Any) -> Any:
    if isinstance(obj, Counter):
        return dict(obj)
    if isinstance(obj, dict):
        return {(k if isinstance(k, str) else " + ".join(x or "base" for x in k)): _jsonable(v)
                for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_jsonable(x) for x in obj]
    return obj


# ── CLI + self-test ──────────────────────────────────────────────────────────

def _selftest() -> None:
    import tempfile
    import numpy as np

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        chats = td / "chats"
        chats.mkdir()
        mem = td / "memory"
        mem.mkdir()

        def transcript(stem, model, adapter, n, with_series=True):
            exs = []
            for i in range(n):
                ex = {"exchange_id": f"{stem}-e{i}", "user_prompt": "u", "assistant_response": "a"}
                if with_series:
                    ex["tension"] = {"token_ids": [1, 2], "entropies": [1, 1], "margins": [0.9, 0.9]}
                exs.append(ex)
            (chats / f"{stem}.json").write_text(json.dumps({
                "timestamp": stem, "model_id": model, "adapter_id": adapter, "exchanges": exs}))

        transcript("20260901_000000", "m1", "/somewhere/models/a1", 4)
        transcript("20260902_000000", "m1", "a1", 3, with_series=False)
        transcript("20260903_000000", "m2", "", 2)
        # sidecars: chat 1 fully reflected (keep, revise, keep-banned, none), chat 3 one keep
        (chats / "20260901_000000.state.json").write_text(json.dumps({
            "reflected_at": "x", "exchanges": {
                "0": {"verdict": "keep"}, "1": {"verdict": "revise", "locked": True},
                "2": {"verdict": "keep", "banned": True}}}))
        (chats / "20260903_000000.state.json").write_text(json.dumps({
            "exchanges": {"0": {"verdict": "keep"}}}))
        # a stray non-transcript json must not be counted
        (chats / "20260901_000000.summary.json").write_text("{}")
        # hidden capture for chat 1 exchanges 0 and 1, with an axis projection
        cap = {"positions": [0, 1], "residuals": {2: np.zeros((2, 4), dtype=np.float16)},
               "axes": {"pain": [0.1, 0.2]}, "n_tokens": 2, "layers": [2], "hidden_dim": 4}
        for i in (0, 1):
            hidden_capture.write_sidecar(chats / "20260901_000000.json", f"20260901_000000-e{i}",
                                         cap, model_id="m1", adapter_id="a1")
        # op-log: three asks (search, user, meta), one resolved, one surfaced twice; a fact
        (mem / "rag_memory.jsonl").write_text("\n".join(json.dumps(r) for r in [
            {"op": "insert", "key": "q1", "kind": "ask", "ask_kind": "search"},
            {"op": "insert", "key": "q2", "kind": "ask", "ask_kind": "user"},
            {"op": "insert", "key": "q3", "kind": "ask", "ask_kind": "meta"},
            {"op": "insert", "key": "f1", "kind": "fact"},
            {"op": "surface", "key": "q2"}, {"op": "surface", "key": "q2"},
            {"op": "evict", "key": "q1"},
        ]))

        rep = build(chats, mem, None, current_model="m1", current_adapter="a1", min_labeled=3)
        c = rep["chats"]
        assert c["transcripts"] == 3 and c["exchanges"] == 9, (c["transcripts"], c["exchanges"])
        g = c["groups"][("m1", "a1")]
        assert g["transcripts"] == 2 and g["exchanges"] == 7 and g["reflected"] == 1
        assert g["verdicts"]["keep"] == 2 and g["verdicts"]["revise"] == 1 and g["verdicts"][""] == 4
        assert g["banned"] == 1 and g["locked"] == 1
        assert g["tension"] == 4 and g["hidden"] == 2 and g["axes"] == 2    # axis members in the sidecar
        assert g["labeled"] == 2 and g["labeled_hidden"] == 2      # keep+revise, ban excluded
        g2 = c["groups"][("m2", "")]
        assert g2["labeled"] == 1 and g2["labeled_hidden"] == 0 and g2["base"] == 0
        assert c["verdict_values"] == ["keep", "revise"]
        a = rep["asks"]
        assert a["live"] == {"user": 1, "meta": 1} and a["resolved"] == {"search": 1}
        assert a["surface_hist"] == {"0": 1, "2": 1}
        r = rep["readiness"]
        assert r["identity"]["labeled"] == 3 and r["identity"]["current_labeled"] == 2
        assert r["identity"]["verdict"].startswith("LABELS EXIST BUT UNDER OTHER WEIGHTS")
        rep2 = build(chats, mem, None, current_model="m1", current_adapter="/else/a1/", min_labeled=2)
        assert rep2["readiness"]["identity"]["verdict"].startswith("READY")
        assert rep2["readiness"]["identity"]["revise_share"] == 1 / 3 and rep2["readiness"]["identity"]["balance_ok"]
        assert "CLASS BALANCE" not in rep2["readiness"]["identity"]["verdict"]
        rep3 = build(chats, mem, None, current_model="m2", current_adapter="", min_labeled=1)
        assert rep3["readiness"]["identity"]["verdict"].startswith("LABELS READY, CAPTURES SHORT")
        assert rep3["readiness"]["identity"]["current_backfillable"] == 1
        # a backfilled (base) capture counts as captured for the probe, apart from live
        hidden_capture.write_sidecar(chats / "20260903_000000.json", "20260903_000000-e0", cap,
                                     model_id="m2", adapter_id="", variant="base")
        c2 = build(chats, mem, None, current_model="m1", current_adapter="a1", min_labeled=3)["chats"]
        g2b = c2["groups"][("m2", "")]
        assert g2b["hidden"] == 0 and g2b["base"] == 1 and g2b["labeled_hidden"] == 1
        assert not r["epistemic"]["ready"] and not r["reset"]["ready"]
        text = render(rep)
        assert "*m1" in text and "keep" in text and "LABELS EXIST" in text
        # a corpus that is all `keep` trips the balance line
        (chats / "20260901_000000.state.json").write_text(json.dumps({
            "exchanges": {"0": {"verdict": "keep"}, "1": {"verdict": "keep"}}}))
        rep4 = build(chats, mem, None, current_model="m1", current_adapter="a1", min_labeled=1)
        assert "CLASS BALANCE" in rep4["readiness"]["identity"]["verdict"]
        json.dumps(_jsonable(rep))   # serializable
    print("label_inventory self-test: OK")


def main(argv: Optional[list] = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(description="Track B label / capture census (read-only).")
    ap.add_argument("--chats", type=Path, default=None, help="transcripts dir (default: the box's)")
    ap.add_argument("--memory", type=Path, default=None, help="reflection memory dir (default: the box's)")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    ap.add_argument("--min-labeled", type=int, default=DEFAULT_MIN_LABELED,
                    help=f"identity floor (default {DEFAULT_MIN_LABELED})")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args(argv)
    if args.selftest:
        _selftest()
        return 0
    chats_dir, memory_dir, attempts, model, adapter = _paths()
    if args.chats is not None:
        chats_dir = args.chats
    if args.memory is not None:
        memory_dir = args.memory
    report = build(chats_dir, memory_dir, attempts, current_model=model,
                   current_adapter=adapter, min_labeled=args.min_labeled)
    if args.json:
        print(json.dumps(_jsonable(report), indent=2, ensure_ascii=False))
    else:
        print(render(report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
